server:
  listen: :8099
  dbg: true
client:
  account_id: secret
  id: secret
  secret: secret
storage:
  type: sqlite
  path: file:data.db?mode=rwc&_journal_mode=WAL
  repository: .tmp # Path to download files