server:
  listen: :8099
  dbg: true
client:
  account_id: secret
  id: secret
  secret: secret
  trash_downloaded: false
  delete_downloaded: false # trumps trash_downloaded
storage:
  type: sqlite
  path: file:.tmp/data1.db?mode=rwc&_journal_mode=WAL
  repository: .tmp # Path to download files
syncable:
    important: ["shared_screen_with_gallery_view"]
    alternative: ["shared_screen_with_speaker_view"]
    optional: ["chat_file"]
    min_duration: 3 # minutes